// Location data
const locationData = {
  wards: [
    "S/GARI",
    "LIKORO",
    "TABA",
    "GARU",
    "K/WALI NORTH",
    "K/WALI SOUTH",
    "DOKA",
    "KUDAN",
    "ZABI",
    "HUNKUYI"
  ],
  villages: {
    "S/GARI": [
      "S/GARIN HUNKUYI",
      "KYAUDAI",
      "MUSAWA",
      "JAJA",
      "DANBAMI"
    ],
    "LIKORO": [
      "LIKORO",
      "S / GARIN LIKORO"
    ],
    "TABA": [
      "TABA",
      "MAHUTA",
      "DANKALA",
      "BAGADI",
      "S/BAGADI"
    ],
    "GARU": [
      "GARU",
      "LAFIYA"
    ],
    "K/WALI NORTH": [
      "KAURAN WALI",
      "BANKANAWA"
    ],
    "K/WALI SOUTH": [
      "S / GARIN KAURA"
    ],
    "DOKA": [
      "DOKA",
      "GUIBI",
      "MAZARA"
    ],
    "KUDAN": [
      "KUDAN",
      "NASARAWA",
      "MATARAWA"
    ],
    "ZABI": [
      "ZABI",
      "DANDAKO"
    ],
    "HUNKUYI": [
      "HUNKUYI",
      "UNGUWAN SARKI",
      "SABO GARI"
    ]
  },
  hamlets: {
    "S/GARIN HUNKUYI": [
      "ANG MALAM",
      "TASHAN FULANI",
      "ANG MAKAMA",
      "SABAN LINE",
      "ANG BARWA",
      "ANG DAN AUDI",
      "ANG AREWACI",
      "ANG DANLAMI",
      "ANG TURAKI",
      "ANG M DUNMUGA",
      "ANG MANI DUNMUGA",
      "ANG DASHI"
    ],
    "KYAUDAI": [
      "ANG SARKI",
      "ANG MAL IDI",
      "ANG BAREBARI",
      "ANG KAJI",
      "ANG KWARI",
      "ANG FULANI",
      "ANG ALASAN"
    ],
    "MUSAWA": [
      "ANG SARKI",
      "ANG MADAKI",
      "ANG GALADIMA",
      "ANG SARAMA  A",
      "DUFA - DUFA",
      "DADIN KOWA",
      "ANG MAIGAYYA",
      "ANG SARAMA  B",
      "ANG ALH BALA",
      "ANG SARKI MATO",
      "ANG MAI KUDAN",
      "ANG ALH AMMA"
    ],
    "JAJA": [
      "ANG ZUBAIRU",
      "ANG WAZIRI",
      "ANG MUAZU",
      "ANG MAKADA",
      "ANG SARKI",
      "TASHAN ICE",
      "ANG FULANI 1",
      "ANG FULANI 2",
      "RURA JAJA",
      "ANG DAN SHAWAI",
      "ANG CHIROMA",
      "ANG MAKARANTA"
    ],
    "DANBAMI": [
      "ANG JARMAI",
      "ANG BALARABE",
      "ANG DAN TSOHO",
      "ANG TANKO",
      "ANG DAN MAKWARWA",
      "ANG KANAWA",
      "ANG SARKI",
      "ANG BELLO",
      "ANG GOBURAWA",
      "ANG MAKERA"
    ],
    "LIKORO": [
      "ANG SARKI",
      "ANG KAROFI",
      "ANG NASARU",
      "ANG KARIMU",
      "ANG GALADIMA",
      "ANG MAKWALLA",
      "ANG K/GABAS",
      "ANG SARKIN RAFI",
      "ANG MAKERA",
      "ANG WALI",
      "ANG MAKAMA",
      "ANG IYA",
      "ANG GRA",
      "HAYIN GADA",
      "ANG MATO",
      "ANG KURNA",
      "ANG DALLADI",
      "KOFAR AREWA",
      "ANG LIMAN",
      "ANG WANZAMAI",
      "ANG RANDA",
      "ANG MAHAUTA",
      "ANG RARIYA"
    ],
    "S / GARIN LIKORO": [
      "ANG KUSHIGI",
      "ANG DOKA",
      "ANG TSAUNI",
      "ANG RAFIN KIRA",
      "ANG MAI-GARI",
      "ANG TSINKA",
      "ANG KUNDI",
      "ANG S/GARIN LIKORO",
      "ANG FULANI",
      "ANG T/WADA",
      "ANG HAYATU B",
      "ANG HAWAN IDI",
      "ANG ALH SHUAIBU S/LIKORO",
      "ANG DANGWANGWANI",
      "ANG BUBAN GIDA",
      "RUGAN ALH BAWA",
      "RUGAN CIROMA",
      "RUGAN CIRKI",
      "RUGAN GORA"
    ],
    "TABA": [
      "ANGUWAN SARKI",
      "ANGUWAN MAGE",
      "ANGUWAN GARBA",
      "ANGUWAN MAKERA",
      "ANGUWAN MADAKI",
      "ANGUWAN BAKIN KASUWA",
      "ANGUWAN GANGARE",
      "ANGUWAN MAHARBA",
      "ANGUWAN MAGAJIN ASKA",
      "ANGUWAN SHARU",
      "ANGUWAN GALADIMA",
      "ANGUWAN FULANI",
      "ANGUWAN SARKI TSOHO",
      "ANGUWAN MABUGA",
      "ANGUWAN SARKINFADA",
      "ANGUWAN MAKARANTA",
      "ANGUWAN YALWA",
      "GIDAN NA DOKA",
      "GIDAN ABABA",
      "GIDAN GERO",
      "RIGAN IBRAHIM MOJO",
      "RIGAN GOMA",
      "SABON GIDA"
    ],
    "MAHUTA": [
      "UNGUWAN SARKI",
      "UNGUWAN LIMAN",
      "UNGUWAN PAMFO",
      "UNGUWAN RIMI",
      "UNGUWAN TAGWAI",
      "SAMBAWA",
      "BABAN GIDA",
      "RANDA",
      "ARUWAYE"
    ],
    "DANKALA": [
      "ANG SARKI",
      "ANG GABASHI",
      "ANG YAMMACI",
      "ANG ACITUWO",
      "ANG JAN WURIYA",
      "ANG HAWAN MAI-MASHI",
      "Unguwan MAL MUSA",
      "Unguwan MAL IBRAHIM",
      "Unguwan ALHAMDU",
      "Unguwan NA ALLAH",
      "GIDAN GANDA",
      "GIDAN JIKA",
      "MASASSAKA",
      "RIGAN JIDDE"
    ],
    "BAGADI": [
      "ANG HAYATU",
      "ANG SARKI A",
      "ANG SARKI B",
      "TASHAR YAU",
      "GWANDAWA",
      "TASHAR DAUDA",
      "ANG NOMAU",
      "ANG MUNKAILA"
    ],
    "S/BAGADI": [
      "ANG TSOHON SARKI",
      "KOFAR KUDU",
      "HAWAN MAI-MASHI",
      "T/HAWAN MAI-MASHI",
      "ANG RINGIM",
      "DUMA KADA-KADA",
      "GIDAN MAI UNGUWAN",
      "RIGAN ABUBAKAR DAUJI"
    ],
    "GARU": [
      "ANG FILLO",
      "ANG DANMALIKI",
      "ANG SAIDU",
      "ANG HARUNA",
      "ANG ABDULSALAM",
      "ANG ALHAJI",
      "ANG CHIROMA",
      "ANG MAKERA",
      "ANG YUSUF",
      "ANG GAMBO",
      "ANG GANGARE",
      "SABON LINE GARU",
      "ANG WAJE",
      "ANG SARKI",
      "ANG DAN DABO",
      "ANG GADIMA",
      "ANG ADAMU",
      "ANG MALAMAI",
      "GIDAN GABAS",
      "ANG MURTALA",
      "CHABEBE",
      "ANG ALARAMMA",
      "ANG ABARAI",
      "ANG UMMARU",
      "GIDAN NAMALIYA",
      "GIDAN NADOGUWA",
      "ANG WALI",
      "ANG WAZIRI",
      "ANG MADAKI GARU",
      "ANG YAHAYA"
    ],
    "LAFIYA": [
      "ANG TURAKI",
      "ANG WAKILI",
      "ANG SARKI",
      "ANG WALI",
      "ANG WAZIRI",
      "ANG CIROMA",
      "ANG UMARU",
      "ANG KATSINAWA",
      "ANG DANGAYYA",
      "ANG SOGA",
      "ANG DANBINNI TSOHOWA",
      "SABON GIDA",
      "ANG DANBINNI SABUWA",
      "ANG MADAKI",
      "ANG KUDU LAFIYA",
      "ANGUWAN HARUNA",
      "RUGAR JAMA'ARE",
      "RUGAR BETI",
      "RUGAR RABO"
    ],
    "KAURAN WALI": [
      "ANG WALI",
      "ANG RUMI 2",
      "ANG RUMI 1",
      "ANG HAMIDU",
      "ANG LIMAN",
      "ANG AMADU",
      "ANG BADARU",
      "ANG KARI",
      "ANG SARKI",
      "ANG SAADU",
      "ANG KAROFI",
      "ANG FAWA A",
      "ANG FAWA B",
      "ANG MAITAKALMI"
    ],
    "BANKANAWA": [
      "T/JIRGI",
      "ANG BANKANAWA",
      "ANG BAKOSHI",
      "ANG T/WADA",
      "S/GARI BANKANAWA",
      "ANG ZAWIYYA",
      "ANG MAKARANTA",
      "ANG MARYAMU",
      "ANG DANBABAI",
      "ANG TATA",
      "TUDUN WADA",
      "ANGUWAN TATA",
      "MARYAMU",
      "ANGUWA YABAI",
      "ANGUWA DANBABAI",
      "ANGUWAN BABA SULE",
      "HAYIN GIWA"
    ],
    "S / GARIN KAURA": [
      "ANG SANDA",
      "ANG BAWA",
      "ANG DAN-DABO",
      "ANG DANJUMA TUMI",
      "ANG TULU",
      "ANG DAN-GASHI",
      "ANG TASHAN MUSA",
      "ANG NAIYA",
      "MAITAKALMI",
      "BAGAGE",
      "RUGAR FULANI ALI",
      "ANGUWAN MAI GWANJO",
      "MAI RAGUNA",
      "GUDUGU",
      "ANGUWAN SODA"
    ],
    "DOKA": [
      "ANG DAN-MAGAJI",
      "ANG MAKERA",
      "ANG LAWAL",
      "ANG RIMI",
      "ANG DAN-MAGANI",
      "ANG LIMAN",
      "ANG M MUSA",
      "ANG SARKI",
      "SABON FEGI",
      "ANG HAKIMI",
      "KOFAR FADA",
      "BAKIN KASUWA",
      "ANG MAKADA",
      "ANG JARIMI",
      "ANG GALADIMA",
      "ANG FILINA",
      "ANG ANAWA",
      "ANG T/LIMAN",
      "ANG S/GARIN DOKA",
      "ANG KOZO",
      "ANG T/TANKO",
      "ANG T/KANAWA",
      "ANG KUDU",
      "ANG M HUSAIN",
      "ANG MAL TUKUR",
      "ANG MAHAUTA",
      "ANG GOBURAWAGA",
      "TUDUN WADA",
      "ANG UKU",
      "ANGUWAR MALAM TUKUR",
      "ANGUWAR MAHAUTA",
      "ANGUWAR GOBURAWAGA",
      "TUDUN WADA",
      "ANGUWAR UKU"
    ],
    "GUIBI": [
      "ANG SARKI",
      "ANG KYANSO",
      "ANG BASHARU",
      "ANG TUDU GUIBI",
      "ANG GABASHI",
      "ANG MAKOYI",
      "ANG SARKI B",
      "ANG BAKIN KOFA",
      "ANG KYADI",
      "ANG TANDA",
      "ANG MAKERA",
      "ANG MAKOYI 2",
      "ANG DANKANDE",
      "ANG NAGUDU",
      "HAYIN SAMAILA",
      "TASHAR DANKANO",
      "DANMAGANI",
      "AREWACI",
      "ANGUWAR MALAM MUSA",
      "KYADI B"
    ],
    "MAZARA": [
      "ANG MASSAKA",
      "ANG LIMAN",
      "ANG DAUDU",
      "ANG DANKWADO",
      "ANG MAKERA",
      "ANG MASALLACI",
      "ANG AREWA KANAWA",
      "ANG SARKI KANAWA",
      "ANG SHEHI KANAWA",
      "KOFAR AREWA KANAWA",
      "ANG TSAUNI KANAWA",
      "S/GARI MAZARA",
      "ANG GANGARE",
      "SABON LAYI",
      "ANG FAWA",
      "ANG BARAU",
      "ANG SARKI ALIYU",
      "ANG KWARI",
      "GIDAN ME JINKA",
      "GIDAN KAUYE",
      "GIDAN KADA",
      "ANGUWAR SARKI ALIYU",
      "ANGUWAR KWARI",
      "GIDAN ME JINKA",
      "GIDAN KAUYE",
      "GIDAN KADA"
    ],
    "KUDAN": [
      "KOFAR FADA",
      "ANG SARKI FADA",
      "ANG ZABI",
      "ANG FUROJA",
      "ANG SARKI",
      "UNG GABAS",
      "ANG BELLO",
      "ANG MAAJI",
      "ANG LIMAN",
      "ANG TATTIBU",
      "ANG SAIDAWA",
      "ANG K/AREWA A",
      "ANG K/AREWA B",
      "ANG NUFAWA",
      "ANG FAWA",
      "ANG KUKA",
      "ANG MAKERA",
      "B/KASUWA",
      "ANG TSAUNI",
      "ANG DAN HAWA",
      "ANG MALAMAI",
      "ANG SHANU",
      "ANG UPE",
      "ANG RIMIN BAIMA",
      "ANG FILOTI",
      "SABON GARI B",
      "SABON GARI A",
      "ANG SHAGARI",
      "ANG GANUWA"
    ],
    "NASARAWA": [
      "MAI GISHIRI",
      "ANG BAKOSHI",
      "ANG SAURON LEMU",
      "ANG NASARAWA",
      "KOFAR FADA",
      "SABON GIDA",
      "GIDAN YARA",
      "GIDAN GAJERA",
      "ANG SOGIJI",
      "ANG RANDA",
      "ANG AJE",
      "SUNDUN FURE",
      "ANG FULANI",
      "ANG GIZARI",
      "ANG TSAMIYA",
      "ANG DAMASKI",
      "LABALO A",
      "LABALO B",
      "GIDAN BIRNI",
      "ANG HULU MOTOR",
      "ANG BURDU",
      "ANG RIMI DAMASKI",
      "SABON GARIN RANDA",
      "GIDAN ALH MAGAJI RANDA"
    ],
    "MATARAWA": [
      "ANG RIMI",
      "ANG JARKASA",
      "ANG MANJA",
      "ANG MAAJI",
      "ANG MAAJI 2",
      "ANG HAYIN SHARA",
      "ANG BUZAYE",
      "ANG TAFAKI",
      "ANG LIMAN",
      "ANG GANUWA",
      "ANG GABARCI",
      "GIDAN MAGODO",
      "GIDAN MAIKWALAMA",
      "RIGAR ARDO"
    ],
    "ZABI": [
      "ANG KUKA",
      "ANG YADI",
      "ANG S/GARIN ZABI",
      "ANG RIMI",
      "ANG KADAGA",
      "ANG KAROFI",
      "ANG HANAU",
      "ANG TASHAR KADE",
      "ANG DANKYAFI",
      "ANG DUTSE",
      "ANG MAIZUMA",
      "ANG DANGOJE R/BISO",
      "ANG BAGOBIRIRI",
      "ANG DAHIRU",
      "TUDUN WADA ZABI",
      "ANG ALH DANLAMI R/BISO",
      "ANG MAKERA",
      "ANG ALH BALA",
      "ANG LASAN",
      "ANG LIMAN MARKU",
      "ANG GOBIRAWA",
      "ANG MAL DAUDA",
      "ANG HALADU",
      "ANG SARKI",
      "ANG MARKU",
      "ANG HUSSAIN",
      "ANG BEBE",
      "ANG HAZAWWA",
      "ANG LAYA",
      "ANG KADAMA"
    ],
    "DANDAKO": [
      "ANG SARKI FADA",
      "ANG LIMANCI",
      "ANG FAWA",
      "ANG KOFAR SHANU",
      "ANG KANGARWA",
      "ANG AMFANI",
      "ANG MAKADA",
      "ANG LIMAN",
      "ANG KAROFI",
      "ANG DANAYA",
      "ANG NAGERO",
      "ANG MAGAJIN ASKA",
      "ANG SABON GIDAN",
      "ANG SHE-SHE",
      "ANG JAE",
      "GIDAN SARKI FULANI",
      "ANG SIDI",
      "ANG HAUTE"
    ],
    "HUNKUYI": [
      "ANG SARKI",
      "ANG WALI",
      "ANG KOFAR KUDU",
      "KOFAR AREWA",
      "ANG GEME",
      "ANG RINGI",
      "ANG RIMI",
      "ANG SA I",
      "TUDUN WADA",
      "ANG SANDA",
      "ANG KUYAWA",
      "ANG DANZANKA B",
      "ANG BAREBARI",
      "ANG SARKIN FADA",
      "ANG MALAMAI",
      "ANG FULANI",
      "ANG WANZAMAI",
      "ANG TUDUN GAMBA",
      "ANG RIMIN GUNDA",
      "ANG JAKADA",
      "ANG BAYAN ASIBITI",
      "ANG HAKIMI",
      "KOFAR YAMMA",
      "ANG DANZANKA A",
      "RAFIN DAWAKI",
      "JAJAN MIKA",
      "KATOGE",
      "ANG KYAUDAN BAKO"
    ],
    "UNGUWAN SARKI": [
      "ANGUWAN MAJEMA",
      "ANGUWAN TUKWANE",
      "SABON LAYI",
      "SABUWAR KASUWA",
      "BAKIN KASUWA",
      "ANGUWAN SAKO"
    ],
    "SABO GARI": [
      "KATOGE",
      "KYAUDAN BAKO",
      "JAJAN MIKA"
    ]
  }
};

export const getWards = () => locationData.wards;

export const getVillagesByWard = (ward: string) => {
  return locationData.villages[ward] || [];
};

export const getHamletsByVillage = (ward: string, village: string) => {
  return locationData.hamlets[village] || [];
}; 